# Malicious keywords that we should be careful about
KEYWORDS = ["word unscrambler",
            "coinhive",
            "attack",
            "lyrics",
            "myspace",
            "free music downloads",
            "phelps",
            "weber-gale",
            "free music",
            "game cheats",
            "printable fill in puzzles",
            "free ringtones",
            "solitaire",
            "bots",
            "miniclip",
            "make money",
            "viva la vida",
            "coldplay",
            "touch my body",
            "lollipop lyrics",
            "love song",
            "my life",
            "weather.com",
            "lowes",
            "the price is right",
            "kimbo slice",
            "metacafe",
            "hotmail.com",
            "bebo",
            "msn.com",
            "music downloads",
            "dailymotion",
            "limewire",
            "paper planes",
            "no air",
            "with you",
            "snopes",
            "wallpapers",
            "free e-cards",
            "text twist",
            "bleeding love",
            "no air by jordin sparks",
            "kijiji",
            "mixed wrestling",
            "zuma rossdale",
            "paris hilton",
            "pamela anderson",
            "free compatibility reports",
            "free people search",
            "song lyrics",
            "coupons",
            "newgrounds",
            "mp3",
            "casey and caylee anthony",
            "costco",
            "corruption",
           ]

EXTENSION = ["a",
             "asm",
             "asp",
             "awk",
             "bat",
             "bmp",
             "btm",
             "BTM",
             "c",
             "class",
             "cmd",
             "cpp",
             "csv",
             "cur",
             "cxx",
             "cxx",
             "conf"
             "db",
             "def",
             "des",
             "dlg",
             "dll",
             "don",
             "dpc",
             "dpj",
             "dtd",
             "dump",
             "dxp",
             "eng",
             "flt",
             "fmt",
             "font",
             "fp",
             "ft",
             "h",
             "hdb",
             "hdl",
             "hid",
             "hpp",
             "hrc",
             "hrc",
             "html",
             "hxx",
             "hxx",
             "hxx",
             "ico",
             "idl",
             "idl",
             "ih",
             "ilb",
             "inc",
             "inf",
             "ini",
             "inl",
             "ins",
             "java",
             "jar",
             "jnl",
             "js",
             "jsp",
             "kdelnk",
             "l",
             "lgt",
             "lib",
             "lin",
             "ll",
             "ln3",
             "lng",
             "lnk",
             "lnx",
             "log",
             "lst",
             "lst",
             "mac",
             "md",
             "macos",
             "map",
             "mk",
             "mk",
             "mod",
             "nt2",
             "o",
             "obj",
             "par",
             "pfa",
             "pfb",
             "pl",
             "pl",
             "plc",
             "pld",
             "pld",
             "plf",
             "pm",
             "pmk",
             "pre",
             "prj",
             "prt",
             "ps",
             "ptr",
             "r",
             "rc",
             "rdb",
             "res",
             "s",
             "sh",
             "sbl",
             "scp",
             "scr",
             "sda",
             "sdb",
             "sdc",
             "sdd",
             "sdg",
             "sdm",
             "sds",
             "sdv",
             "sdw",
             "sdi",
             "seg",
             "seg",
             "set",
             "sgl",
             "sh",
             "sid",
             "smf",
             "sms",
             "so",
             "soh",
             "sob",
             "soc",
             "sod",
             "sh",
             "soe",
             "sog",
             "soh",
             "src",
             "srs",
             "ssleay",
             "static",
             "tab",
             "tfm",
             "thm",
             "tpt",
             "tsc",
             "ttf",
             "ttf",
             "txt",
             "txt",
             "unx",
             "unx",
             "urd",
             "url",
             "vms",
             "vor",
             "w32",
             "wa",
             "wmf",
             "xml",
             "xpm",
             "xrb",
             "y",
             "yxx"
            ]